name: beplus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  mime: ^1.0.0
  http: ^0.13.3
  flutter:
    sdk: flutter
  mailer: ^4.0.0
  otp_timer_button: ^1.0.0
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.5
  path: ^1.8.0
  mongo_dart: ^0.8.2
  path_provider: ^2.1.5
  icons_plus: ^5.0.0
  url_launcher: ^6.1.7
  google_sign_in: ^6.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.0.0
  image_picker: ^0.8.4+5
  permission_handler: ^11.3.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  intl: ^0.17.0
  firebase_auth: ^5.2.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  geolocator: ^12.0.0
  webview_flutter: ^4.9.0
  table_calendar: ^3.1.2
  booking_range_slider: ^0.0.1
  lottie: ^2.0.0
  http_parser: ^4.0.2
  share_plus: ^10.1.3
  pdf: ^3.11.1
  flutter_pdfview: ^1.3.4
  firebase_performance: ^0.10.0+8
  material_design_icons_flutter: ^5.0.0
  horizontal_week_calendar: ^0.0.18
dependency_overrides:
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/assets/fonts/Roboto-Black.ttf
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/BE+.png"
